monsters["Force Dragon (Juvenile)"] = 
{'Subtypes': 'force',
"Level Adjustment": "-",
"Space": "20 ft",
"Reach": "15 ft (20 ft with bite)",
"Full Attack": "bite +47 melee (4d6+43) and 2 claws +42 melee (2d8+21) and 2 wings +42 melee (2d6+21) and 1 tail slap +42 melee (2d8+21)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['4d6+43', '2d8+21', '2d6+21', '2d8+21'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'force'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "forceDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '30', 'Hit Points': '542', 'Grapple': '+63', 'Total Attack Bonus': ['+47', '+42'], 'Ref': '+19', 'Challenge Rating': '25', 'Armor Class -- Flat-footed': '50', 'Hit Dice': '35', 'Fort': '+28', 'Dex': '10', 'Base Attack': '+35', 'Armor Class -- Touch': '16', 'Armor Class: deflection': '+10', 'Will': '+29', 'Spell/Power Resistance': '33', 'Armor Class: natural': '+34', 'Str': '43', 'Con': '29', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'damage reduction 15/magic', 'resilient sphere', 'blur', 'caster lvl 12th'], 'Int': '30', 'Armor Class': '50', 'Wis': '31', 'Speed': ['60 ft', 'fly 300 ft (clumsy)'], 'Size': 'gargantuan'};
monsters["Force Dragon (Young Adult)"] = 
{'Subtypes': 'force',
"Level Adjustment": "-",
"Space": "20 ft",
"Reach": "15 ft (20 ft with bite)",
"Full Attack": "bite +54 melee (4d6+47) and 2 claws +49 melee (2d8+23) and 2 wings +49 melee (2d6+23) and 1 tail slap +49 melee (2d8+23)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['4d6+47', '2d8+23', '2d6+23', '2d8+23'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'force'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "forceDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '34', 'Hit Points': '700', 'Grapple': '+70', 'Total Attack Bonus': ['+54', '+49'], 'Ref': '+22', 'Challenge Rating': '28', 'Armor Class -- Flat-footed': '57', 'Hit Dice': '40', 'Fort': '+33', 'Dex': '10', 'Base Attack': '+40', 'Armor Class -- Touch': '18', 'Armor Class: deflection': '+12', 'Will': '+34', 'Spell/Power Resistance': '36', 'Armor Class: natural': '+39', 'Str': '47', 'Con': '33', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'damage reduction 15/magic', 'resilient sphere', 'blur', 'damage reduction 15/epic', 'caster lvl 15th'], 'Int': '34', 'Armor Class': '57', 'Wis': '35', 'Speed': ['60 ft', 'fly 300 ft (clumsy)'], 'Size': 'gargantuan'};
monsters["Force Dragon (Old)"] = 
{'Subtypes': 'force',
"Level Adjustment": "-",
"Space": "30 ft",
"Reach": "20 ft (30 ft with bite)",
"Full Attack": "bite +71 melee (4d8+59) and 2 claws +66 melee (4d6+29) and 2 wings +66 melee (2d8+29) and 1 tail slap +66 melee (4d6+29)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['4d8+59', '4d6+29', '2d8+29', '4d6+29'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'force'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "forceDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '46', 'Hit Points': '1292', 'Grapple': '+95', 'Total Attack Bonus': ['+71', '+66'], 'Ref': '+29', 'Challenge Rating': '37', 'Armor Class -- Flat-footed': '74', 'Hit Dice': '55', 'Fort': '+46', 'Dex': '10', 'Base Attack': '+55', 'Armor Class -- Touch': '20', 'Armor Class: deflection': '+18', 'Will': '+47', 'Spell/Power Resistance': '45', 'Armor Class: natural': '+54', 'Str': '59', 'Con': '45', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'damage reduction 15/magic', 'resilient sphere', 'blur', 'damage reduction 15/epic', 'wall of force', 'damage reduction 20/epic', 'forcecage', 'displacement', 'caster lvl 24th'], 'Int': '46', 'Armor Class': '74', 'Wis': '47', 'Speed': ['60 ft', 'fly 300 ft (clumsy)'], 'Size': 'colossal'};
monsters["Force Dragon (Mature Adult)"] = 
{'Subtypes': 'force',
"Level Adjustment": "-",
"Space": "30 ft",
"Reach": "20 ft (30 ft with bite)",
"Full Attack": "bite +64 melee (4d8+55) and 2 claws +59 melee (4d6+27) and 2 wings +59 melee (2d8+27) and 1 tail slap +59 melee (4d6+27)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['4d8+55', '4d6+27', '2d8+27', '4d6+27'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'force'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "forceDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '42', 'Hit Points': '1075', 'Grapple': '+88', 'Total Attack Bonus': ['+64', '+59'], 'Ref': '+27', 'Challenge Rating': '35', 'Armor Class -- Flat-footed': '67', 'Hit Dice': '50', 'Fort': '+42', 'Dex': '10', 'Base Attack': '+50', 'Armor Class -- Touch': '18', 'Armor Class: deflection': '+16', 'Will': '+43', 'Spell/Power Resistance': '42', 'Armor Class: natural': '+49', 'Str': '55', 'Con': '41', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'damage reduction 15/magic', 'resilient sphere', 'blur', 'damage reduction 15/epic', 'wall of force', 'damage reduction 20/epic', 'caster lvl 21st'], 'Int': '42', 'Armor Class': '67', 'Wis': '43', 'Speed': ['60 ft', 'fly 300 ft (clumsy)'], 'Size': 'colossal'};
monsters["Force Dragon (Young)"] = 
{'Subtypes': 'force',
"Level Adjustment": "-",
"Space": "20 ft",
"Reach": "15 ft (20 ft with bite)",
"Full Attack": "bite +40 melee (4d6+39) and 2 claws +35 melee (2d8+19) and 2 wings +35 melee (2d6+19) and 1 tail slap +35 melee (2d8+19)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['4d6+39', '2d8+19', '2d6+19', '2d8+19'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'force'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "forceDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '26', 'Hit Points': '405', 'Grapple': '+56', 'Total Attack Bonus': ['+40', '+35'], 'Ref': '+17', 'Challenge Rating': '21', 'Armor Class -- Flat-footed': '43', 'Hit Dice': '30', 'Fort': '+24', 'Dex': '10', 'Base Attack': '+30', 'Armor Class -- Touch': '14', 'Armor Class: deflection': '+8', 'Will': '+25', 'Spell/Power Resistance': '30', 'Armor Class: natural': '+29', 'Str': '39', 'Con': '25', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'damage reduction 15/magic', 'caster lvl 9th'], 'Int': '26', 'Armor Class': '43', 'Wis': '27', 'Speed': ['60 ft', 'fly 300 ft (clumsy)'], 'Size': 'gargantuan'};
monsters["Force Dragon (Very Young)"] = 
{'Subtypes': 'force',
"Level Adjustment": "-",
"Space": "15 ft",
"Reach": "10 ft (15 ft with bite)",
"Full Attack": "bite +35 melee (2d8+35) and 2 claws +30 melee (2d6+17) and 2 wings +30 melee (1d8+17) and 1 tail slap +30 melee (2d6+17)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['2d8+35', '2d6+17', '1d8+17', '2d6+17'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'force'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "forceDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '22', 'Hit Points': '312', 'Grapple': '+45', 'Total Attack Bonus': ['+35', '+30'], 'Ref': '+14', 'Challenge Rating': '19', 'Armor Class -- Flat-footed': '38', 'Hit Dice': '25', 'Fort': '+20', 'Dex': '10', 'Base Attack': '+25', 'Armor Class -- Touch': '14', 'Armor Class: deflection': '+6', 'Will': '+20', 'Spell/Power Resistance': '27', 'Armor Class: natural': '+24', 'Str': '35', 'Con': '23', 'Special Attacks': ['breath weapon', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'caster lvl 6th'], 'Int': '22', 'Armor Class': '38', 'Wis': '23', 'Speed': ['60 ft', 'fly 250 ft (poor)'], 'Size': 'huge'};
monsters["Force Dragon (Wyrmling)"] = 
{'Subtypes': 'force',
"Level Adjustment": "-",
"Space": "15 ft",
"Reach": "10 ft (15 ft with bite)",
"Full Attack": "bite +28 melee (2d8+31) and 2 claws +23 melee (2d6+15) and 2 wings +23 melee (1d8+15) and 1 tail slap +23 melee (2d6+15)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['2d8+31', '2d6+15', '1d8+15', '2d6+15'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'force'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "forceDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '18', 'Hit Points': '230', 'Grapple': '+38', 'Total Attack Bonus': ['+28', '+23'], 'Ref': '+12', 'Challenge Rating': '13', 'Armor Class -- Flat-footed': '31', 'Hit Dice': '20', 'Fort': '+17', 'Dex': '10', 'Base Attack': '+20', 'Armor Class -- Touch': '12', 'Armor Class: deflection': '+4', 'Will': '+16', 'Spell/Power Resistance': '24', 'Armor Class: natural': '+19', 'Str': '31', 'Con': '21', 'Special Attacks': ['breath weapon', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'caster lvl 3rd'], 'Int': '18', 'Armor Class': '31', 'Wis': '19', 'Speed': ['60 ft', 'fly 250 ft (poor)'], 'Size': 'huge'};
monsters["Force Dragon (Ancient)"] = 
{'Subtypes': 'force',
"Level Adjustment": "-",
"Space": "30 ft",
"Reach": "20 ft (30 ft with bite)",
"Full Attack": "bite +85 melee (4d8+67) and 2 claws +80 melee (4d6+33) and 2 wings +80 melee (2d8+33) and 1 tail slap +80 melee (4d6+33)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['4d8+67', '4d6+33', '2d8+33', '4d6+33'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'force'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "forceDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '54', 'Hit Points': '1787', 'Grapple': '+109', 'Total Attack Bonus': ['+85', '+80'], 'Ref': '+34', 'Challenge Rating': '43', 'Armor Class -- Flat-footed': '88', 'Hit Dice': '65', 'Fort': '+55', 'Dex': '10', 'Base Attack': '+65', 'Armor Class -- Touch': '24', 'Armor Class: deflection': '+22', 'Will': '+56', 'Spell/Power Resistance': '51', 'Armor Class: natural': '+64', 'Str': '67', 'Con': '53', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'damage reduction 15/magic', 'resilient sphere', 'blur', 'damage reduction 15/epic', 'wall of force', 'damage reduction 20/epic', 'forcecage', 'displacement', 'damage reduction 25/epic', 'maze', 'caster lvl 30th'], 'Int': '54', 'Armor Class': '88', 'Wis': '55', 'Speed': ['60 ft', 'fly 300 ft (clumsy)'], 'Size': 'colossal'};
monsters["Force Dragon (Very Old)"] = 
{'Subtypes': 'force',
"Level Adjustment": "-",
"Space": "30 ft",
"Reach": "20 ft (30 ft with bite)",
"Full Attack": "bite +78 melee (4d8+63) and 2 claws +73 melee (4d6+31) and 2 wings +73 melee (2d8+31) and 1 tail slap +73 melee (4d6+31)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['4d8+63', '4d6+31', '2d8+31', '4d6+31'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'force'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "forceDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '50', 'Hit Points': '1530', 'Grapple': '+102', 'Total Attack Bonus': ['+78', '+73'], 'Ref': '+32', 'Challenge Rating': '39', 'Armor Class -- Flat-footed': '81', 'Hit Dice': '60', 'Fort': '+51', 'Dex': '10', 'Base Attack': '+60', 'Armor Class -- Touch': '22', 'Armor Class: deflection': '+20', 'Will': '+52', 'Spell/Power Resistance': '48', 'Armor Class: natural': '+59', 'Str': '63', 'Con': '49', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'damage reduction 15/magic', 'resilient sphere', 'blur', 'damage reduction 15/epic', 'wall of force', 'damage reduction 20/epic', 'forcecage', 'displacement', 'damage reduction 25/epic', 'caster lvl 27th'], 'Int': '50', 'Armor Class': '81', 'Wis': '51', 'Speed': ['60 ft', 'fly 300 ft (clumsy)'], 'Size': 'colossal'};
monsters["Force Dragon (Great Wyrm)"] = 
{'Subtypes': 'force',
"Level Adjustment": "-",
"Space": "30 ft",
"Reach": "20 ft (30 ft with bite)",
"Full Attack": "bite +99 melee (8d6+75) and 2 claws +94 melee (4d8+37) and 2 wings +94 melee (4d6+37) and 1 tail slap +94 melee (4d8+37)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['8d6+75', '4d8+37', '4d6+37', '4d8+37'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'force'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "forceDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '62', 'Hit Points': '2362', 'Grapple': '+123', 'Total Attack Bonus': ['+99', '+94'], 'Ref': '+39', 'Challenge Rating': '59', 'Armor Class -- Flat-footed': '102', 'Hit Dice': '75', 'Fort': '+64', 'Dex': '10', 'Base Attack': '+75', 'Armor Class -- Touch': '28', 'Armor Class: deflection': '+26', 'Will': '+65', 'Spell/Power Resistance': '57', 'Armor Class: natural': '+74', 'Str': '75', 'Con': '61', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'damage reduction 15/magic', 'resilient sphere', 'blur', 'damage reduction 15/epic', 'wall of force', 'damage reduction 20/epic', 'forcecage', 'displacement', 'damage reduction 25/epic', 'maze', 'telekinetic sphere', 'invisibility', 'caster lvl 36th'], 'Int': '62', 'Armor Class': '102', 'Wis': '63', 'Speed': ['60 ft', 'fly 350 ft (clumsy)'], 'Size': 'colossal+'};
monsters["Force Dragon (Adult)"] = 
{'Subtypes': 'force',
"Level Adjustment": "-",
"Space": "20 ft",
"Reach": "15 ft (20 ft with bite)",
"Full Attack": "bite +61 melee (4d6+51) and 2 claws +56 melee (2d8+25) and 2 wings +56 melee (2d6+25) and 1 tail slap +56 melee (2d8+25)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['4d6+51', '2d8+25', '2d6+25', '2d8+25'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'force'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "forceDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '38', 'Hit Points': '877', 'Grapple': '+77', 'Total Attack Bonus': ['+61', '+56'], 'Ref': '+24', 'Challenge Rating': '31', 'Armor Class -- Flat-footed': '64', 'Hit Dice': '45', 'Fort': '+37', 'Dex': '10', 'Base Attack': '+45', 'Armor Class -- Touch': '20', 'Armor Class: deflection': '+14', 'Will': '+38', 'Spell/Power Resistance': '39', 'Armor Class: natural': '+44', 'Str': '51', 'Con': '37', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'damage reduction 15/magic', 'resilient sphere', 'blur', 'damage reduction 15/epic', 'wall of force', 'caster lvl 18th'], 'Int': '38', 'Armor Class': '64', 'Wis': '39', 'Speed': ['60 ft', 'fly 300 ft (clumsy)'], 'Size': 'gargantuan'};
monsters["Force Dragon (Wyrm)"] = 
{'Subtypes': 'force',
"Level Adjustment": "-",
"Space": "30 ft",
"Reach": "20 ft (30 ft with bite)",
"Full Attack": "bite +92 melee (8d6+71) and 2 claws +87 melee (4d8+35) and 2 wings +87 melee (4d6+35) and 1 tail slap +87 melee (4d8+35)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['8d6+71', '4d8+35', '4d6+35', '4d8+35'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'force'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "forceDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '58', 'Hit Points': '2065', 'Grapple': '+116', 'Total Attack Bonus': ['+92', '+87'], 'Ref': '+37', 'Challenge Rating': '50', 'Armor Class -- Flat-footed': '95', 'Hit Dice': '70', 'Fort': '+60', 'Dex': '10', 'Base Attack': '+70', 'Armor Class -- Touch': '26', 'Armor Class: deflection': '+24', 'Will': '+61', 'Spell/Power Resistance': '54', 'Armor Class: natural': '+69', 'Str': '71', 'Con': '57', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'damage reduction 15/magic', 'resilient sphere', 'blur', 'damage reduction 15/epic', 'wall of force', 'damage reduction 20/epic', 'forcecage', 'displacement', 'damage reduction 25/epic', 'maze', 'caster lvl 33rd'], 'Int': '58', 'Armor Class': '95', 'Wis': '59', 'Speed': ['60 ft', 'fly 350 ft (clumsy)'], 'Size': 'colossal+'};
monsters["Prismatic Dragon (Juvenile)"] = 
{'Subtypes': 'light',
"Level Adjustment": "-",
"Space": "20 ft",
"Reach": "15 ft (20 ft with bite)",
"Full Attack": "bite +49 melee (4d6+41) and 2 claws +44 melee (2d8+20) and 2 wings +44 melee (2d6+20) and 1 tail slap +44 melee (2d8+20)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['4d6+41', '2d8+20', '2d6+20', '2d8+20'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'light', 'blindness'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "prismaticDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '32', 'Hit Points': '665', 'Grapple': '+65', 'Total Attack Bonus': ['+49', '+44'], 'Ref': '+21', 'Challenge Rating': '30', 'Armor Class -- Flat-footed': '54', 'Hit Dice': '38', 'Fort': '+32', 'Dex': '10', 'Base Attack': '+38', 'Armor Class -- Touch': '17', 'Armor Class: deflection': '+11', 'Will': '+32', 'Spell/Power Resistance': '42', 'Armor Class: natural': '+37', 'Str': '41', 'Con': '33', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'hypnotic pattern', 'damage reduction 15/magic', 'rainbow pattern', 'caster lvl 13th'], 'Int': '32', 'Armor Class': '54', 'Wis': '33', 'Speed': ['60 ft', 'fly 300 ft (clumsy)'], 'Size': 'gargantuan'};
monsters["Prismatic Dragon (Young Adult)"] = 
{'Subtypes': 'light',
"Level Adjustment": "-",
"Space": "20 ft",
"Reach": "15 ft (20 ft with bite)",
"Full Attack": "bite +56 melee (4d6+45) and 2 claws +51 melee (2d8+22) and 2 wings +51 melee (2d6+22) and 1 tail slap +51 melee (2d8+22)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['4d6+45', '2d8+22', '2d6+22', '2d8+22'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'light', 'blindness'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "prismaticDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '36', 'Hit Points': '838', 'Grapple': '+72', 'Total Attack Bonus': ['+56', '+51'], 'Ref': '+23', 'Challenge Rating': '34', 'Armor Class -- Flat-footed': '61', 'Hit Dice': '43', 'Fort': '+36', 'Dex': '10', 'Base Attack': '+43', 'Armor Class -- Touch': '19', 'Armor Class: deflection': '+13', 'Will': '+36', 'Spell/Power Resistance': '48', 'Armor Class: natural': '+42', 'Str': '45', 'Con': '37', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'hypnotic pattern', 'damage reduction 15/magic', 'rainbow pattern', 'damage reduction 15/epic', 'caster lvl 17th'], 'Int': '36', 'Armor Class': '61', 'Wis': '37', 'Speed': ['60 ft', 'fly 300 ft (clumsy)'], 'Size': 'gargantuan'};
monsters["Prismatic Dragon (Old)"] = 
{'Subtypes': 'light',
"Level Adjustment": "-",
"Space": "30 ft",
"Reach": "20 ft (30 ft with bite)",
"Full Attack": "bite +73 melee (4d8+57) and 2 claws +68 melee (4d6+28) and 2 wings +68 melee (2d8+28) and 1 tail slap +68 melee (4d6+28)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['4d8+57', '4d6+28', '2d8+28', '4d6+28'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'light', 'blindness'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "prismaticDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '48', 'Hit Points': '1479', 'Grapple': '+97', 'Total Attack Bonus': ['+73', '+68'], 'Ref': '+31', 'Challenge Rating': '48', 'Armor Class -- Flat-footed': '78', 'Hit Dice': '58', 'Fort': '+50', 'Dex': '10', 'Base Attack': '+58', 'Armor Class -- Touch': '21', 'Armor Class: deflection': '+19', 'Will': '+50', 'Spell/Power Resistance': '66', 'Armor Class: natural': '+57', 'Str': '57', 'Con': '49', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'hypnotic pattern', 'damage reduction 15/magic', 'rainbow pattern', 'damage reduction 15/epic', 'sunbeam', 'damage reduction 20/epic', 'sunburst', 'caster lvl 26th'], 'Int': '48', 'Armor Class': '78', 'Wis': '49', 'Speed': ['60 ft', 'fly 300 ft (clumsy)'], 'Size': 'colossal'};
monsters["Prismatic Dragon (Mature Adult)"] = 
{'Subtypes': 'light',
"Level Adjustment": "-",
"Space": "30 ft",
"Reach": "20 ft (30 ft with bite)",
"Full Attack": "bite +66 melee (4d8+53) and 2 claws +61 melee (4d6+26) and 2 wings +61 melee (2d8+26) and 1 tail slap +61 melee (4d6+26)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['4d8+53', '4d6+26', '2d8+26', '4d6+26'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'light', 'blindness'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "prismaticDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '44', 'Hit Points': '1245', 'Grapple': '+90', 'Total Attack Bonus': ['+66', '+61'], 'Ref': '+28', 'Challenge Rating': '43', 'Armor Class -- Flat-footed': '71', 'Hit Dice': '53', 'Fort': '+45', 'Dex': '10', 'Base Attack': '+53', 'Armor Class -- Touch': '19', 'Armor Class: deflection': '+17', 'Will': '+45', 'Spell/Power Resistance': '60', 'Armor Class: natural': '+52', 'Str': '53', 'Con': '45', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'hypnotic pattern', 'damage reduction 15/magic', 'rainbow pattern', 'damage reduction 15/epic', 'sunbeam', 'damage reduction 20/epic', 'caster lvl 23rd'], 'Int': '44', 'Armor Class': '71', 'Wis': '45', 'Speed': ['60 ft', 'fly 300 ft (clumsy)'], 'Size': 'colossal'};
monsters["Prismatic Dragon (Young)"] = 
{'Subtypes': 'light',
"Level Adjustment": "-",
"Space": "20 ft",
"Reach": "15 ft (20 ft with bite)",
"Full Attack": "bite +42 melee (4d6+37) and 2 claws +37 melee (2d8+18) and 2 wings +37 melee (2d6+18) and 1 tail slap +37 melee (2d8+18)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['4d6+37', '2d8+18', '2d6+18', '2d8+18'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'light', 'blindness'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "prismaticDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '28', 'Hit Points': '511', 'Grapple': '+58', 'Total Attack Bonus': ['+42', '+37'], 'Ref': '+18', 'Challenge Rating': '22', 'Armor Class -- Flat-footed': '47', 'Hit Dice': '33', 'Fort': '+27', 'Dex': '10', 'Base Attack': '+33', 'Armor Class -- Touch': '15', 'Armor Class: deflection': '+9', 'Will': '+27', 'Spell/Power Resistance': '36', 'Armor Class: natural': '+32', 'Str': '37', 'Con': '29', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'hypnotic pattern', 'damage reduction 15/magic', 'caster lvl 11th'], 'Int': '28', 'Armor Class': '47', 'Wis': '29', 'Speed': ['60 ft', 'fly 300 ft (clumsy)'], 'Size': 'gargantuan'};
monsters["Prismatic Dragon (Very Young)"] = 
{'Subtypes': 'light',
"Level Adjustment": "-",
"Space": "15 ft",
"Reach": "10 ft (15 ft with bite)",
"Full Attack": "bite +37 melee (2d8+33) and 2 claws +32 melee (2d6+16) and 2 wings +32 melee (1d8+16) and 1 tail slap +32 melee (2d6+16)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['2d8+33', '2d6+16', '1d8+16', '2d6+16'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'light', 'blindness'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "prismaticDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '24', 'Hit Points': '378', 'Grapple': '+47', 'Total Attack Bonus': ['+37', '+32'], 'Ref': '+16', 'Challenge Rating': '16', 'Armor Class -- Flat-footed': '42', 'Hit Dice': '28', 'Fort': '+23', 'Dex': '10', 'Base Attack': '+28', 'Armor Class -- Touch': '15', 'Armor Class: deflection': '+7', 'Will': '+23', 'Spell/Power Resistance': '30', 'Armor Class: natural': '+27', 'Str': '33', 'Con': '25', 'Special Attacks': ['breath weapon', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'hypnotic pattern', 'caster lvl 8th'], 'Int': '24', 'Armor Class': '42', 'Wis': '25', 'Speed': ['60 ft', 'fly 250 ft (poor)'], 'Size': 'huge'};
monsters["Prismatic Dragon (Wyrmling)"] = 
{'Subtypes': 'light',
"Level Adjustment": "-",
"Space": "15 ft",
"Reach": "10 ft (15 ft with bite)",
"Full Attack": "bite +30 melee (2d8+29) and 2 claws +25 melee (2d6+14) and 2 wings +25 melee (1d8+14) and 1 tail slap +25 melee (2d6+14)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['2d8+29', '2d6+14', '1d8+14', '2d6+14'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'light', 'blindness'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "prismaticDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '20', 'Hit Points': '287', 'Grapple': '+40', 'Total Attack Bonus': ['+30', '+25'], 'Ref': '+13', 'Challenge Rating': '14', 'Armor Class -- Flat-footed': '35', 'Hit Dice': '23', 'Fort': '+19', 'Dex': '10', 'Base Attack': '+23', 'Armor Class -- Touch': '13', 'Armor Class: deflection': '+5', 'Will': '+18', 'Spell/Power Resistance': '24', 'Armor Class: natural': '+22', 'Str': '29', 'Con': '23', 'Special Attacks': ['breath weapon', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'hypnotic pattern', 'caster lvl 5th'], 'Int': '20', 'Armor Class': '35', 'Wis': '21', 'Speed': ['60 ft', 'fly 250 ft (poor)'], 'Size': 'huge'};
monsters["Prismatic Dragon (Ancient)"] = 
{'Subtypes': 'light',
"Level Adjustment": "-",
"Space": "30 ft",
"Reach": "20 ft (30 ft with bite)",
"Full Attack": "bite +87 melee (8d6+65) and 2 claws +82 melee (4d8+32) and 2 wings +82 melee (4d6+32) and 1 tail slap +82 melee (4d8+32)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['8d6+65', '4d8+32', '4d6+32', '4d8+32'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'light', 'blindness'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "prismaticDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '56', 'Hit Points': '2006', 'Grapple': '+111', 'Total Attack Bonus': ['+87', '+82'], 'Ref': '+36', 'Challenge Rating': '57', 'Armor Class -- Flat-footed': '92', 'Hit Dice': '68', 'Fort': '+59', 'Dex': '10', 'Base Attack': '+68', 'Armor Class -- Touch': '25', 'Armor Class: deflection': '+23', 'Will': '+59', 'Spell/Power Resistance': '74', 'Armor Class: natural': '+67', 'Str': '65', 'Con': '57', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'hypnotic pattern', 'damage reduction 15/magic', 'rainbow pattern', 'damage reduction 15/epic', 'sunbeam', 'damage reduction 20/epic', 'sunburst', 'damage reduction 25/epic', 'prismatic wall', 'caster lvl 32nd'], 'Int': '56', 'Armor Class': '92', 'Wis': '57', 'Speed': ['60 ft', 'fly 350 ft (clumsy)'], 'Size': 'colossal+'};
monsters["Prismatic Dragon (Very Old)"] = 
{'Subtypes': 'light',
"Level Adjustment": "-",
"Space": "30 ft",
"Reach": "20 ft (30 ft with bite)",
"Full Attack": "bite +80 melee (4d8+61) and 2 claws +75 melee (4d6+30) and 2 wings +75 melee (2d8+30) and 1 tail slap +75 melee (4d6+30)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['4d8+61', '4d6+30', '2d8+30', '4d6+30'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'light', 'blindness'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "prismaticDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '52', 'Hit Points': '1732', 'Grapple': '+104', 'Total Attack Bonus': ['+80', '+75'], 'Ref': '+33', 'Challenge Rating': '52', 'Armor Class -- Flat-footed': '85', 'Hit Dice': '63', 'Fort': '+54', 'Dex': '10', 'Base Attack': '+63', 'Armor Class -- Touch': '23', 'Armor Class: deflection': '+21', 'Will': '+54', 'Spell/Power Resistance': '68', 'Armor Class: natural': '+62', 'Str': '61', 'Con': '53', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'hypnotic pattern', 'damage reduction 15/magic', 'rainbow pattern', 'damage reduction 15/epic', 'sunbeam', 'damage reduction 20/epic', 'sunburst', 'damage reduction 25/epic', 'caster lvl 29th'], 'Int': '52', 'Armor Class': '85', 'Wis': '53', 'Speed': ['60 ft', 'fly 300 ft (clumsy)'], 'Size': 'colossal'};
monsters["Prismatic Dragon (Great Wyrm)"] = 
{'Subtypes': 'light',
"Level Adjustment": "-",
"Space": "30 ft",
"Reach": "20 ft (30 ft with bite)",
"Full Attack": "bite +101 melee (8d6+73) and 2 claws +96 melee (4d8+36) and 2 wings +96 melee (4d6+36) and 1 tail slap +96 melee (4d8+36)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['8d6+73', '4d8+36', '4d6+36', '4d8+36'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'light', 'blindness'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "prismaticDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '64', 'Hit Points': '2613', 'Grapple': '+125', 'Total Attack Bonus': ['+101', '+96'], 'Ref': '+41', 'Challenge Rating': '66', 'Armor Class -- Flat-footed': '106', 'Hit Dice': '78', 'Fort': '+68', 'Dex': '10', 'Base Attack': '+78', 'Armor Class -- Touch': '29', 'Armor Class: deflection': '+27', 'Will': '+68', 'Spell/Power Resistance': '86', 'Armor Class: natural': '+77', 'Str': '73', 'Con': '65', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'hypnotic pattern', 'damage reduction 15/magic', 'rainbow pattern', 'damage reduction 15/epic', 'sunbeam', 'damage reduction 20/epic', 'sunburst', 'damage reduction 25/epic', 'prismatic wall', 'prismatic sphere', 'caster lvl 38th'], 'Int': '64', 'Armor Class': '106', 'Wis': '65', 'Speed': ['60 ft', 'fly 350 ft (clumsy)'], 'Size': 'colossal+'};
monsters["Prismatic Dragon (Adult)"] = 
{'Subtypes': 'light',
"Level Adjustment": "-",
"Space": "30 ft",
"Reach": "20 ft (30 ft with bite)",
"Full Attack": "bite +59 melee (4d8+49) and 2 claws +54 melee (4d6+24) and 2 wings +54 melee (2d8+24) and 1 tail slap +54 melee (4d6+24)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['4d8+49', '4d6+24', '2d8+24', '4d6+24'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'light', 'blindness'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "prismaticDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '40', 'Hit Points': '1032', 'Grapple': '+83', 'Total Attack Bonus': ['+59', '+54'], 'Ref': '+26', 'Challenge Rating': '39', 'Armor Class -- Flat-footed': '64', 'Hit Dice': '48', 'Fort': '+41', 'Dex': '10', 'Base Attack': '+48', 'Armor Class -- Touch': '17', 'Armor Class: deflection': '+15', 'Will': '+41', 'Spell/Power Resistance': '54', 'Armor Class: natural': '+47', 'Str': '49', 'Con': '41', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'hypnotic pattern', 'damage reduction 15/magic', 'rainbow pattern', 'damage reduction 15/epic', 'sunbeam', 'caster lvl 20th'], 'Int': '40', 'Armor Class': '64', 'Wis': '41', 'Speed': ['60 ft', 'fly 300 ft (clumsy)'], 'Size': 'colossal'};
monsters["Prismatic Dragon (Wyrm)"] = 
{'Subtypes': 'light',
"Level Adjustment": "-",
"Space": "30 ft",
"Reach": "20 ft (30 ft with bite)",
"Full Attack": "bite +94 melee (8d6+69) and 2 claws +89 melee (4d8+34) and 2 wings +89 melee (4d6+34) and 1 tail slap +89 melee (4d8+34)",
"Attacks per Round": "6",
"Weapons (melee)": ['bite', 'claw', 'wing', 'tail slap'],
"Damage": ['8d6+69', '4d8+34', '4d6+34', '4d8+34'],
"Source": "epic level handbook",
"Blindsense": "60 ft.",
"Darkvision": "120 ft.",
"Hit Die": "d12",
"Initiative": "+0",
"Treasure": "triple standard",
"Immunities": ['sleep', 'paralysis', 'light', 'blindness'],
"Alignment - Free Will": "usually",
"Alignment - Ethics": "neutral",
"Alignment - Morals": "neutral",
"Type": "dragon",
">file": "dragonEpic",
">anchor": "prismaticDragon",
"listen": "class skill",
"search": "class skill",
"spot": "class skill",
"concentration": "class skill",
"diplomacy": "class skill",
"escape artist": "class skill",
"intimidate": "class skill",
"knowledge (any)": "class skill",
"sense motive": "class skill",
"use magic device": "class skill",
'Cha': '60', 'Hit Points': '2299', 'Grapple': '+118', 'Total Attack Bonus': ['+94', '+89'], 'Ref': '+38', 'Challenge Rating': '61', 'Armor Class -- Flat-footed': '99', 'Hit Dice': '73', 'Fort': '+63', 'Dex': '10', 'Base Attack': '+73', 'Armor Class -- Touch': '27', 'Armor Class: deflection': '+25', 'Will': '+63', 'Spell/Power Resistance': '80', 'Armor Class: natural': '+72', 'Str': '69', 'Con': '61', 'Special Attacks': ['breath weapon', 'tail sweep', 'crush', 'frightful presence'], 'Special Qualities': ['damage reduction 10/magic', 'deflecting force', 'hypnotic pattern', 'damage reduction 15/magic', 'rainbow pattern', 'damage reduction 15/epic', 'sunbeam', 'damage reduction 20/epic', 'sunburst', 'damage reduction 25/epic', 'prismatic wall', 'caster lvl 35th'], 'Int': '60', 'Armor Class': '99', 'Wis': '61', 'Speed': ['60 ft', 'fly 350 ft (clumsy)'], 'Size': 'colossal+'};
